import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const iowan = localFont({
  src: "./iowan-bold.ttf",
  display: "swap",
  variable: '--font-iowan'
})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WalletWise - Personal Finances",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${iowan.variable}`}>{children}</body>
    </html>
  );
}
